### ISSUE TITLE
è abbandonato il progetto?

### ISSUE THREAD

**Issue by lucnap** [italia/fatturapa-php-sdk#10]
è abbandonato il progetto?

**Comment by simevo** [comment]
Ciao Luciano e grazie per l'interesse, stiamo lavorando attivamente per supportare la fatturazione elettronica B2B in PHP.
Su questo repo in effetti c'è poca attività, ti consiglio di guardare [qui](https://github.com/italia/fatturapa-testsdi) e [qui](https://github.com/simevo/fatturapa-testui).
Inloltre ti invito ad unirti al canale `#fatturapa` su https://slack.developers.italia.it/ per discutere di questi temi !

**Comment by digitall-it** [comment]
Il link https://slack.developers.italia.it/ al momento non è funzionante, come è possibile segnalarlo? Mi piacerebbe collaborare al progetto.

**Comment by simevo** [comment]
L'ho segnalato e la risposta del teamdigitale 3 gg fa è stata "ne siamo al corrente, vediamo di sistemare al più presto!"

**Comment by simevo** [comment]
Ciao @lucnap  il link su https://slack.developers.italia.it/ è tornato online, rinnovo l'invito a unirti al canale #fatturapa !
